Clinical-Genomics/demultiplexing

scripts/hiseqx/index2sample.py
To determine a possible contamination we needed to correlate
possible contaminated lanes with their samples.
Ran like this:
```
ls -1 ${DEMUX}/mnt/hds/proj/bioinfo/DEMUX/*/LOG/?.index* | \
xargs grep -l $CONTAMINANT | \
xargs -I {} python index2sample.py {} $CONTAMINANT
```
This will get all precalculated undetermined indexes files, feed those files to grep in search of the contaminant, then feed the matching files to belowmentioned script.
This script is a one-of and will most likely not be reused.
=> Add index2sample.py

demux/cli/samplesheet.py, scripts/checkfornewrun.bash
(cherry picked from commit c60c5c5f74e752f4e753c707e73b4c0b52b2c441)
When we multiplex samples on a flowcell, we are allowed to use different length indexes in the same lane. This requires to demultiplex several times, once for each index length. This part of the package retrieves the samples with indexes from LIMS and formats those into a samplesheet we can use for demultiplexing. We now want to be able to select the samples which have either the longest of the shortest index length.
Somehow the min/max functions with custom comparators doesn't make for easy reading.
=> Add shortest index option in sheet fetch CLI

scripts/novaseq/checkfornewrun.bash
Two instances of bcl2fastq running at the same time in current configuration will grind the server to a halt. This is the simplest queue :)
=> Add check to stop demux when one is already running

scripts/novaseq/demux-novaseq.bash
Fixes error during post processing and renaming of files when a sample has zero reads and no fastq-file is created by bcl2fastq.
How to test:
1. clone on thalamus and comment out everything that has to do with demulitplexing or cgstats in the demux-novaseq.bash
2. `rm /home/hiseq.clinical/STAGE/novaseq/runs/181207_A00187_0091_AH3CJ3DRXX/demuxstarted.txt`
2.5 (if needed) `mv /home/hiseq.clinical/STAGE/novaseq/demux/181207_A00187_0091_AH3CJ3DRXX/Unaligned-Y151I8I8Y151/Project_indexcheck /home/hiseq.clinical/STAGE/novaseq/demux/181207_A00187_0091_AH3CJ3DRXX/Unaligned-Y151I8I8Y151/indexcheck`
3. `bash checkfornewrun.bash /home/hiseq.clinical/STAGE/novaseq/runs /home/hiseq.clinical/STAGE/novaseq/demux`
Expected outcome:
No errors while running and …
=> fix renaming of non-existing fastq files in projects

scripts/2-hiseq-deliver.bash
Some improvements over previous edition:
- if the transfer fails for any reason, remove the copycomplete.txt so the transfer starts again on next crontab iteration. Helps mitigate network failures.
- Send an email as soon as rasta transfer is finished. Send another when hasta transfer is finished.
How to test:
0. Install this branch in a local repo on thalamus: ~/git/demultiplexing
1. This one is configuration heavy, so
- change the destination of TARGET_DIR_HASTA= to /home/proj/stage/demultiplexed-runs
- change the EMAILS= to your email address.
2. remove `~/STAGE/novaseq/demux/181207_A00187_0091_AH3CJ3DRXX/copycomplete.txt`
3. `bash ~/git/demulitplexing/scripts/2-hiseq-deliver.bash ~/STAGE//novaseq/demux/181207_A00187_0091_AH3CJ3DRXX rasta /mnt/hds/proj/bioinfo/STAGE/DEMUX/`
4. while …
=> Sync to rasta and hasta from thalamus

demux/cli/samplesheet.py
Problem: The new unique dual indexes that CG will use to prepare TGA and microbial samples are 10+10 bp long (d10) while our current unique dual indexes for WGS are only 8+8bp (d8). That means that we need to run demultiplexing of FC with a mix of these index types twice. This take a lot of time and involves manual labour.
Suggested solution:
When we create the samplesheet (demux sheet fetch -a nova flowcell_id) we can add two extra bases to the d8 indexes, so that all samples in a run have d10 indexes for demultiplexing. The bases are static (AT for index1, AC for index2). The adding of these two bases shall henceforth be known as padding ;)
Added option -p or --pad for padding
Added error message in case -p is provided but not indexlength (--shortest, --longest or --indexlength)
Added …
=> add padding option of d8 indexes

scripts/novaseq/checkfornewrun.bash
--pad option was added to `demux sheet fetch` for novaseq, now added it to the cron script too.
=> add --pad option to checkfornewrun.bash

demux/cli/samplesheet.py
How to test:
1. clone
1. on thalamus, run: `demux sheet fetch -a wes HWWK2BCX2`: out put is empty sheet
1. in your own conda env, install demux, set alias demux to this env
1. run `demux sheet fetch -a wes HWWK2BCX2`: output is now a full sheet
=> Fix outputting an empty sheet when no index lenght set

scripts/2-hiseq-deliver.bash
Removes the emails sent when data is successfully transferred to hasta and rasta.
How to test:
0. install on stage on thalamus:
`git clone -b rm-delivered-emails https://github.com/Clinical-Genomics/demultiplexing.git ~/git/<yourname>/demux/`
1. disable syncing: `crontab -e` comment out the line after `# delivery 2500 results`
1. `rm /home/hiseq.clinical/DEMUX/190308_D00410_0865_AHWLKTBCX2/copycomplete.txt`
1. run: `bash ~/git/<yourname>/demux/scripts/2-hiseq-deliver.bash`
1. enable syncing again
Expected outcome:
syncing should happen and the output should not mention
`column -t /home/hiseq.clinical/DEMUX//190308_D00410_0865_AHWLKTBCX2/stats-*`
after
`scp /home/hiseq.clinical/DEMUX//190308_D00410_0865_AHWLKTBCX2/copycomplete.txt …
=> Rm delivered emails

scripts/novaseq/demux-novaseq.bash
Demux faster by using more cores!
How To test:
0. clone on thalamus: `git clone -b more-cores https://github.com/clinical-genomics/demultiplexing ~/git/<yourname>/demultiplexing`
1. Run `bash ~/git/<yourname>/emux-novaseq.bash ~/STAGE/novaseq/runs/190129_A00689_0008_BHHGYWDSXX ~/STAGE/novaseq/demux/`
Expected outcome:
- demux succeeds
- when you expect the project log in ` ~/STAGE/novaseq/demux/190129_A00689_0008_BHHGYWDSXX` the time should be less then 12 hours
Outcome:
```
...
[20190415093351] Here we go!
...
[20190415182509] cgstats select --project indexcheck
```
w00t w00t! It only took 9 hours!
=> Harder faster forever after

scripts/2-hiseq-deliver.bash
This PR removes syncing to rasta
How to test:
1. Clone this branch on clinical-preproc: `git clone -b rm-rasa https://github.com/clinical-genomics/demultiplexing.git ~/git/yourname/demultiplexing/
1. Run: `bash ~/git/yourname/demultiplexing/scripts/bash 2-hiseq-deliver.bash ${HOME}/novaseq/demux/ hasta.scilifelab.se /home/proj/production/demultiplexed-runs/ your.name@scilifelab.se`
Expected outcome:
no errors! :)
This is a patch version: hotfix to make sure TEAPOT is not flushed with errors
=> Rm sync to rasta

demux/cli/samplesheet.py, demux/utils/__init__.py, demux/utils/samplesheet.py
This PR solves the retrieval of the iSeq samplesheet.
**How to test?**
1. `bash update-demux-stage.sh isheet` on clinical-preproc stage.
1. run: `demux sheet fetch -a iseq --pad --indexlength 10 $flowcell`
with $flowcell BPC29611-2526 or BPC29611-3324 (see comment below)
**Expected outcome**
The fecth command will print the samplesheet to stdout. The samplesheet should contain an index and index2 column. index should end with AT and index2 should start with AC.
Headers should be: 
Sample_Name | Sample_Plate | Description | I7_Index_ID | index | I5_Index_ID | index2 | Manifest | GenomeFolder | Sample_Project | Sample_Well
This is **minor version** bump: extending and not modifying public API.
@emiliaol can you provide a FC id?
=> Add iSeq retrieval

demux/utils/__init__.py, demux/utils/samplesheet.py, scripts/iseq/checkfornewrun.bash, scripts/iseq/demux-iseq.bash
This PR adds demuliplexing support for iSeq
**How to setup**:
1. install on stage of thalamus: `bash servers/resources/clinical-preproc.scilifelab.se/update-demux-stage.sh Automatic-demultiplexing-of-iSeq-runs`
1. cd cd /home/hiseq.clinical/SCRIPTS/git/demultiplexing/
1. git pull
1. git checkout Automatic-demultiplexing-of-iSeq-runs
1. activate stage: source activate stage
1. cd /home/hiseq.clinical/SCRIPTS/git/demultiplexing/scripts/iseq/
**How to test demultiplexing**:
1. run following command: ` bash demux-iseq.bash /home/hiseq.clinical/iseq/runs/20190528_FS10000534_7_BPC29611-3324/ /home/hiseq.clinical/iseq/demux/`
**Expected outcome**:
**How to test checking for new run**:
1. run following command: `bash checkfornewrun.bash /home/hiseq.clinical/iseq/runs/ …
=> Automatic demultiplexing of iseq runs

scripts/2-hiseq-deliver.bash
This PR removes syncing of Undetermined files from thalamus to hasta.
**How to test on thalamus**:
1. On hasta: `rm /home/proj/stage/demultiplexed-runs/190208_A00689_0009_AHHMGWDSXX/Unaligned-Y151I10I10Y151/Undetermined*`
On thalamus:
1. install on locally: `cd ~/git/yourname/; git clone git+https://github.com/clinical-genomics/demultiplexing@exclude`
1. remove the copycomplete.txt files: `rm ~/STAGE/novaseq/demux/*/copycomplete.txt`
1. run following command: `bash /home/hiseq.clinical/git/yourname/demultiplexing/scripts/2-hiseq-deliver.bash /home/hiseq.clinical/STAGE/novaseq/demux/ hasta.scilifelab.se /home/proj/stage/demultiplexed-runs/`
**Expected outcome**:
After a few hours check `hasta.scilifelab.se:/home/proj/stage/demultiplexed-runs/`. Following runs should be synced:
- …
=> Exclude Undetermined files from rsync

scripts/hiseqx/xdemuxtiles.bash
This PR fixes the missing account for the post-script, which at this point fails the demux. It seems like I (I guess?) had patched this quickly in production a while ago (foei foei foei!), so this is the PR to actually make those changes official and tested.
1. install on stage
1. activate stage: `us`
1. run following command: `bash xdemuxtiles.bash /home/proj/production/flowcells/hiseqx/180907_ST-E00269_0299_AHNYKJCCXY/`
**Expected outcome**:
demux should start without errors.
**Review:**
This is patch **version bump** because no new functionality was added.
=> Add qos to xdemuxtiles.bash

scripts/novaseq/checkfornewrun.bash
This PR removes a run condition from starting a novaseq demux
- get two run folders ready by removing the demuxstarted.txt
- modify the checkfornewrun.bash script by not really calling the demux-novaseq.bash script, rather just echo that it was called (to avoid actually to have to demux)
- run checkfornewrun.bash 
**Expected outcome**:
Only one run should "start" (echo)
**Review:**
This is patch **version bump** because this fixes an edge case bug.
=> fix: run once and only once

demux/cli/base.py
This PR fixes PyYAML yaml.load(input) Deprecation
`bash servers/resources/clinical-preproc.scilifelab.se/update-demux-stage.sh yaml-load`
context.obj = yaml.load(config) if config else {}` does not appear
**Review:**
=> Fix PyYAML yaml.load(input) Deprecation

demux/cli/samplesheet.py
This PR adds/fixes:
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh [THIS-BRANCH-NAME]`
**Review:**
=> temp fix for path to dummy indices

demux/basemask.py, demux/cli/samplesheet.py, demux/utils/samplesheet.py, scripts/novaseq/checkfornewrun.bash
This PR fixes production deviation #129 where demultiplexing failed due to an empty sample sheet in one of the runs directories.
`bash servers/resources/clinical-preproc.scilifelab.se/update-demux-stage.sh fix-empty-samplesheet`
**Review:**
=> Fix empty samplesheet

scripts/novaseq/checkfornewrun.bash
If we start demultiplexing when the file `CopyComplete.txt` is present, we prevent the demultiplexing from starting before syncing is fully complete.
This prevents duplicate reads from showing up due to temporary bcl files still being present, but also prevents demultiplexing failing due to missing/corrupted bcl files caused by a lag in the syncing from sequencer -> NAS -> thalamus. Two birds with one stone.
`RTAComplete.txt` indicates that all the bcl have been created *on the sequencer* for a particular run
`CopyComplete.txt` indicates that all data has been synced to the NAS from the sequencer, and the tmp bcl files have been removed.
Why did we only check for `RTAComplete.txt`?
1) the use of `CopyComplete.txt` was added as a feature at a later stage (only several years ago /s)
2) it …
=> Check for CopyComplete.txt to prevent duplicate reads in analysis

demux/utils/novaseq_samplesheet.py
Emergency fix for https://github.com/Clinical-Genomics/demultiplexing/pull/123
=> emergency fix index1

scripts/novaseq/checkfornewrun.bash
This PR adds/fixes the test for removing an empty samplesheet before fetching a new one, leading to an error email being sent without cause: `ERROR starting novaseq HCTCNDSXY on clinical-preproc.scilifelab.se, line 56`
```
[hiseq.clinical@thalamus 201203_A00689_0200_AHVKJCDRXX]$ bash /home/hiseq.clinical/STAGE/git/demultiplexing/scripts/novaseq/checkfornewrun.bash /home/hiseq.clinical/STAGE/novaseq/runs/ /home/hiseq.clinical/STAGE/novaseq/demux/
rm: cannot remove `/home/hiseq.clinical/STAGE/novaseq/runs//201203_A00689_0200_AHVKJCDRXX/SampleSheet.csv': No such file or directory
cat: /home/hiseq.clinical/STAGE/novaseq/demux//201203_A00689_0200_AHVKJCDRXX/projectlog.20201215112907.log: No such file or directory
Null message body; hope that's ok
demux sheet fetch …
```
=> Fix empty sample sheet test in novaseq demux script

CONTRIBUTING.md, container/bcl2fastq/Dockerfile
This PR adds/fixes:
- See above
**Expected outcome**
**Review:**
=> feat(docker): Adds a bcl2fastq docker recipe

scripts/novaseq/checkfornewrun.bash, scripts/novaseq/stage/checkfornewrun.bash
The script https://github.com/Clinical-Genomics/deliver/blob/master/scripts/checkfornewdemuxonhasta.bash looks for both copycomplete.txt and demuxcomplete.txt to start post demux actions. For novaseq flowcells these actions are limited to adding the flowcell to HK (by running `cg transfer flowcell <flowcell_id`) and sending out an email indicating the the run is complete.
The file copycomplete.txt was previously added by the script https://github.com/Clinical-Genomics/demultiplexing/blob/98b5d9f5dff9d5bd932db98c32c3dbf422a73b11/scripts/2-hiseq-deliver.bash on thalamus that synced the demux directory on thalamus to the demultiplexed-runs directory on hasta.
This fix makes sure a copycomplete.txt is added to the run directory in demultiplexed-runs. It also remove any existing delivery.txt …
=> fix novaseq demux script to enable automated post demux actions

pyproject.toml
This PR fixes corrupted `pyproject.toml`, causing error during deployment.
**Expected test outcome
**Review:**
=> fix weirdness caused by bumpversion typo

scripts/2500/NIPT/syncnipt.bash, scripts/2500/stage/NIPT/syncnipt.bash
This PR fixes the use of `^M` in a `sed` command in the script `syncnipt.bash`. `^M` stands for carriage return, in the sample sheet a carriage return needs to be replaced with a new line `\n`, and for some reason the symbol `^M` can end up as an actual hard return in the code 😡 
=> Fix carriage return in sed command in syncnipt script

demux/constants/samplesheet.py, demux/utils/novaseq_samplesheet.py, demux/utils/runparameters.py
Control versions and kit versions were previously checked to be a specific one. However, after discussions with @AnnaZetterlund and @barrystokman we came to the conclusion that we should check if these are at least of the same or newer version.
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh control_and_reagent_version_fix`
**Review:**
=> Version check for updates to Novaseq versions

demux/cli/basemask.py
Read cycles for HiSeqX was hardcoded, this pr makes it so that it is determined from runParameters.xml
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh fix-hiseqx-basemask-read-cycles`
**Review:**
=> Count read cycles from runParameters.xml

demux/cli/basemask.py
Updating the base mask as we get an error message in demultiplexing right now:
```"UseBasesMask formatting error. Use base mask must start with either a 'y', 'i', or 'n'. Use base mask: '151'".```
`bash /home/proj/stage/servers/resources/hasta.scilifelab.se/update-demux-stage.sh Add-Y-to-base-mask`
**Review:**
=> Add Y to base mask

scripts/hiseqx/xdemuxtiles.batch
This PR removes Undetermined files from HiSeqX demultiplexing output. This saves space since these old undetermined files where never used.
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh hiseqx-never-link-pooled-undetermined`
**Review:**
=> Removing linking of pooled HiSeqX Undermined fastq-files

demux/cli/samplesheet.py, scripts/hiseqx/xdemuxtiles.batch
This PR actually does what should have been done in https://github.com/Clinical-Genomics/demultiplexing/pull/158
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh hiseqx-never-link-pooled-undetermined`
**Review:**
=> Hiseqx never link pooled undetermined

demux/cli/samplesheet.py
This PR fixes a bug implemented by https://github.com/Clinical-Genomics/demultiplexing/pull/153/files. The variable was removed since it was not used in the code but the `click.option` remained. 
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh fix/remove-end-option`
**Review:**
=> fix(removed --end option)

pyproject.toml
This fixes a poetry bug implemented on the version
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh [THIS-BRANCH-NAME]`
**Review:**
=> fix(poetry.toml version)
